demo2/demo2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('polls.urls')),
]

demo2/polls/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.list),
    url(r'^detail/(\d+)/$', views.detail),
    url(r'^result/$', views.result),

]

demo2/polls/models.py
from django.db import models


class Question(models.Model):
    qname = models.CharField(max_length=255)

    def __str__(self):
        return self.qname


class Choose(models.Model):
    cname = models.CharField(max_length=20)
    cvote = models.IntegerField(default=0)
    cques = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.cname

demo2/polls/views.py
from django.shortcuts import render
from .models import Question,Choose
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.


def list(request):
    queslist = Question.objects.all()
    return render(request, 'polls/list.html', {'queslist': queslist})


def detail(request, quesid):
    ques = Question.objects.get(pk=quesid)
    return render(request, 'polls/detail.html', {'ques': ques})

def result(request):
    quesid = request.POST["quesid"]
    ques = Question.objects.get(pk=quesid)
    qvote = request.POST["vote"]
    choose = Choose.objects.get(pk=qvote)
    choose.cvote += 1
    choose.save()
    return render(request, 'polls/result.html', {'ques': ques})

demo2/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div>
        <h2>问题：{{ques.qname}}</h2>
        <ul>
            投票选项：<br><br>
            <form action="/result/" method="post">
                {% for choose in ques.choose_set.all %}
                    <li><input type="radio" name="vote" value="{{choose.id}}">{{choose}}</li>
                {% endfor %}
                <br><input type="submit" value="投票">
                <input type="hidden" value="{{ques.id}}" name="quesid">
            </form>

        </ul>
    </div>


</body>
</html>

demo2/templates/polls/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h2>投票信息</h2>
        <ul>
            {% for ques in queslist %}
                <li><a href="/detail/{{ques.id}}/">{{ques.qname}}</a></li><br>
            {% empty %}
                暂无投票问题
            {% endfor %}
        </ul>
    </div>

</body>
</html>

demo2/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div>
        <ul>
            <h2>问题：{{ques.qname}}</h2>
            <h3>投票结果：</h3>
            {% for choose in ques.choose_set.all %}
                <li>{{choose.cname}}--{{choose.cvote}}</li>
            {% endfor %}
        </ul>
        <a href="/">返回首页</a>
    </div>
</body>
</html>

demo2/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题列表页</title>
</head>
<body>
    <h2>问题:{{ ques.qname}}</h2>
    <ul>
        <h3>投票结果：</h3>
        {% for choose in ques.choose_set.all %}
            <li>{{choose.cname}}--{{choose.cvote}}</li>
        {% endfor %}
    </ul>

</body>
</html>