demo1/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^delete/(\d+)/$', views.delete, name='delete'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^addherohandle/$', views.addherohandle, name='addherohandle'),
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('booktest.urls', namespace='booktest'))
]

demo1/booktest/models.py
from django.db import models


class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.btitle


class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=100)
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

    def name(self):
        return self.hname

    name.short_description = '角色'

    def sex(self):
        return self.hgender

    sex.short_description = '性别'

    def skill(self):
        return self.hcontent

    skill.short_description = '绝招'

demo1/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import BookInfo, HeroInfo
from django.template import loader


def index(request):

    return render(request, 'booktest/index.html', {'username': 'xcy'})
    # temp = loader.get_template('booktest/index.html')
    # result = temp.render({'username': 'xcy'})
    # print(result, type(result))
    # return HttpResponse(result)


def list(request):
    bl = BookInfo.objects.all()
    return render(request, 'booktest/list.html', {'booklist': bl})
    # temp = loader.get_template('booktest/list.html')
    # result = temp.render({'bname': '连城诀', 'pub_time': '2000年'})
    # return HttpResponse(result)


def detail(request, id):
    book = BookInfo.objects.get(pk=int(id))
    return render(request, 'booktest/detail.html', {'book': book})
    # try:
    #     return HttpResponse(BookInfo.objects.get(pk=int(id)))
    # # return HttpResponse('详情页'+str(id))
    # except:
    #     return HttpResponse('请输入正确的图书id')


def delete(request, id):
    # return HttpResponse('删除成功')
    BookInfo.objects.get(pk=id).delete()
    bl = BookInfo.objects.all()
    # return render(request, 'booktest/list.html', {'booklist': bl})
    return HttpResponseRedirect('/list/', {'booklist': bl})


def addhero(request, bookid):
    # return HttpResponse('角色添加成功')
    # books = BookInfo.objects.all()
    return render(request, 'booktest/addhero.html', {'bookid': bookid})


def addherohandle(request):
    bookid = request.POST['bookid']
    # bookid =5
    hname = request.POST["hname"]
    hgender = request.POST["hgender"]
    hcontent = request.POST["hcontent"]

    book = BookInfo.objects.get(pk=bookid)

    h = HeroInfo()
    h.hname = hname
    h.hgender = hgender
    h.hcontent = hcontent
    h.hbook = book

    h.save()

    return HttpResponseRedirect('/detail/'+str(bookid), {'book': book})

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加角色</title>
</head>
<body>

    <form action="{% url 'booktest:addherohandle' %}" method="post">
        <input type="hidden" value="{{bookid}}" name="bookid">

        角色名字：<input type="text" name="hname">
        <br><br>
        角色性别：<input type="radio" value=True name="hgender" checked>True <input type="radio" value=False name="hgender">False
        <br><br>
        角色技能：<input type="text" name="hcontent">
        <br><br>
        <input type="submit" value="添加">
    </form>
</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
    <h3>图书：{{book.btitle}}</h3>
    <ul>
        {% for hero in book.heroinfo_set.all %}
            <li>{{hero.hname}}--{{hero.hcontent}}</li>
        {% empty %}
            <span>暂时没有角色</span>
        {% endfor %}
        <!--<a href="/list/">返回列表页</a>-->
        <!--<a href="{% url 'booktest:addhero' book.id %}">添加角色</a>-->
        <a href="{% url 'booktest:addhero' book.id%}">添加角色</a><br><br>
        <a href="{% url 'booktest:list' %}">返回列表页</a>

    </ul>

</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        {% if username %}
            <h2>{{username}}</h2>
        {% else %}
            <h2>没有用户登录</h2>
        {% endif %}
        <img src="/static/img/314630.jpg" alt="图片加载失败" width="1100px">
        <!--<a href="/list/">进入列表页</a>-->
        <a href="{% url 'booktest:list' %}">进入列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
</head>
<body>
    <ul>
        {% for book in booklist %}

            <li>
                <a href="{% url 'booktest:detail' book.id %}">{{book.btitle}}</a>
                <a href="{% url 'booktest:delete' book.id %}">删除</a>

            </li>
        {% empty %}
            <span>暂时没有图书信息</span>
        {% endfor %}


        <a href="/">返回首页</a>
    </ul>
</body>
</html>